### ISSUE TITLE
Generate paraphrases for a new dataset

### ISSUE THREAD

**Issue by mmmjung** [malllabiisc/DiPS#13]
Hello, thanks for the code!

I'd like to achieve the following:
- train your model for the best effectiveness (or at least quite good effectiveness)
- generate let's say 5 paraphrases for each sentence in a dataset (eg TREC dataset from https://github.com/harvardnlp/sent-conv-torch/tree/master/data)

What are the exact steps for this?

**Comment by ashutoshml** [comment]
Please go through README.md.
