### ISSUE TITLE
How to generate multiple paraphrases for a question

### ISSUE THREAD

**Issue by krutikabapat** [malllabiisc/DiPS#16]
I wanted to know what are the required changes to be done in order to get more than one paraphrased questions for a given question. :D

**Comment by ashutoshml** [comment]
The training will be as before.

Just set beam_width  = number of paraphrases you want for a given sentence during "decoding". (Try to keep it <10). Otherwise, you'll have to modify inner_width also (inside model.py)

Let me know if that works

**Comment by krutikabapat** [comment]
@ashutoshml Thanks a lot for your prompt response.
