### ISSUE TITLE
Can this method be used for other languages?

### ISSUE THREAD

**Issue by wang-na** [malllabiisc/DiPS#18]
Hi, Thank you for sharing the code!
I want to know whether this code can be used for Chinese?
If I want to use the code for Chinese data augmentaion, which part should I change?
Thank you!

**Comment by ashutoshml** [comment]
Hi @wang-na 

Apologies, but it will be difficult for me to answer that question. I have not worked with Chinese/Mandarin datasets so far.
The code has been tested on English Language, only. If the tokenization and general overlap (with word-embeddings) structure of chinese language is similar, then I think this should work. 

You would need to provide a parallel dataset for training, and (optionally) chinese token embeddings for calculating $L_2$ (as described in the paper)

Thanks!

**Comment by wang-na** [comment]
Hi, Thank you for your quick reply.
OK, I'll try it for Chinese following your suggestion~
Thank again!
