### ISSUE TITLE
Remove "pkg-resources==0.0.0" from requirements.txt

### ISSUE THREAD

**Issue by fabriceyhc** [malllabiisc/DiPS#27]
`pkg-resources==0.0.0` causes `pip install -r requirements.txt` to fail (on windows). 

According to this [link](https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command), it should be safe to just remove it from `requirements.txt`.

**Comment by ashutoshml** [comment]
@fabriceyhc 
Thanks for creating this issue and providing a link to the StackOverflow question.
I tested the code on some earlier configurations on Ubuntu 16.04.

I'll keep the same `requirements.txt` file and point to this issue in case others face similar problems.
