### ISSUE TITLE
Creating new paraphrases

### ISSUE THREAD

**Issue by thefirebanks** [malllabiisc/DiPS#3]
Thank you for uploading this code! 

I just finished training the model and would like to know how could I use it to generate new sentences based on unseen sentence seeds? 

Say I have a text file src.txt containing 3 sentences, and I would like to generate 2 or 3 paraphrases for each of those sentences. I saw that the decode mode of the main.py file requires a src.txt and a tgt.txt files, but is it possible to do it without the tgt.txt? Many thanks in advance.

**Comment by thefirebanks** [comment]
Temporarily ended up using random sentences in a tgt.txt file and everything worked.

**Comment by krutikabapat** [comment]
@thefirebanks Thanks a lot. I am also stuck in the same issue. Can you please tell me what exactly do you mean by random sentences in the tgt.txt file? I am also facung the same question of "what to keep in the tgt.txt file" while making it run for my own custome dataset. Thanks in advance 👯‍♂️

**Comment by thefirebanks** [comment]
Absolutely! To be honest, I just wrote random things such as "asdasdasdasd" per each line of the source sentence. Hope this works!
