### ISSUE TITLE
Question: Using a pre-trained encoder?

### ISSUE THREAD

**Issue by Stamenov** [malllabiisc/DiPS#4]
Is there any reason or limitation why one could not use BERT or other Transformer-based encoders for:
1) Word vector generation instead of word2vec 
2) Use directly the encoder and only train the decoder part?

Best

**Comment by ashutoshml** [comment]
Hi @Stamenov,

One could use _any_ kind of encoder-decoder network for training. As discussed in the paper, submodularity comes into effect **only** during the inference/decoding stage. One only needs to incorporate the submodular objective during the beam search for that. Please refer to the code for a quick overview of how to do it.

1. As far as I remember, we use the word2vec model for embedding similarity (Equation 7 in the paper). There is no restriction on using other word vectors that exhibit better _similarity_ per se.

2. Sure. In principle, that is possible.

Let me know in case this needs further clarifications

Regards
