### ISSUE TITLE
Link to Quora-Div doesnt work

### ISSUE THREAD

**Issue by Stamenov** [malllabiisc/DiPS#5]
Link to Quora-Div doesnt work, could you please update it. Thanks.

**Comment by ashutoshml** [comment]
Hi @Stamenov,

Can you specifically let me know the error?

I checked the link. It seems to be working for me. 
I think you might need to create a Microsoft account. 

Regards

**Comment by Stamenov** [comment]
I was able to download the twitter, but not the quora one. Now both work, not sure what happened. Same setup. Anyways, thanks for the quick reply.
