### ISSUE TITLE
how to measure BLEU and other metrices

### ISSUE THREAD

**Issue by toruurakawa** [malllabiisc/DiPS#9]
Hi,

I am trying to do the experiment of section 5 in [the paper](https://www.aclweb.org/anthology/N19-1363/), using evaluation scripts in [src/evaluation/](https://github.com/malllabiisc/DiPS/tree/master/src/evaluation), but now I am struggling to reproduce results of table 4 and 5. 

The model trained with Twitter gave almost the same results (BLEU:47-56, lambda:0.5-1), however the model trained with Quora-Div had a BLEU of **21-26** (lambda:0.5-1), which was lower than that of the paper (**35.1**).

Here are the outputs of src/evaluation/get_bleu_score.py to the decoding results of quora-div test data.
> \# lambda = 0.5
>  results_submod_src_0.5_1.0_1.0_1.0_1.0.npy : (0.2133832613042971, [0.5514513662938855, 0.2794985741291888, 0.16517278760476983, 0.10313060915605508], 0.9426644403664957, 0.9442470265324794, 516031, 546500)
> \# lambda = 1.0
> results_submod_src_1.0_1.0_1.0_1.0_1.0.npy : (0.2677655774938234, [0.6150636401998018, 0.3489407079357134, 0.22080072282389715, 0.14503831657417837], 0.92996373353237, 0.9323055809698079, 509505, 546500)

In my setup, the seq2seq model was trained using the quora-div data set with same hyperparameter settings as the ones in [the supplementary material](https://www.aclweb.org/anthology/attachments/N19-1363.Supplementary.pdf), the w2v dictionary was created using a trained embedding, and each decoding was done with beam=10.

Would you provide detailed information about conducting the experiment, including procedures such as how to calculate bleu for each ref and candidates pairs (like getting average of the all candidates or max value of them)? 

I also would like to know how you measure METEOR and TERp scores in the paper. (libraries or other OSSs you used for calculating them)

Thanks

**Comment by ashutoshml** [comment]
Hi @toruurakawa 

While the script in the code is given for BLEU-4 (with bp). The results reported in the paper were of BLEU-2 (up to bigrams) as mentioned in the paper. You can use any standard bleu evaluation package for that. 

For eg.
https://www.nltk.org/_modules/nltk/translate/bleu_score.html

Please set the weights as (0.5,0.5,0,0) for bigram measurement scores.  You should be able to get much better scores, if not close.

Please check and let me know.

**Comment by toruurakawa** [comment]
Thank you so much for your fast reply, @ashutoshml 

I'm sorry, I missed it in the paper.

I got better results than the one in the paper as you said, with bigram evaluation using nltk.
> results_submod_src_1.0_1.0_1.0_1.0_1.0.npy : [0.4313678430484928]

And thank you for telling me about METEOR and TERp, too.
I'll check them soon and re-open the issue if I have something about them.
